export const ADMIN_VIEW_IDS = {
  HOME: {
    SECTION: "admin-home-section",
    HEADING: "admin-home-heading",
    DESCRIPTION: "admin-home-description",
  },
  ABOUT: {
    SECTION: "admin-about-section",
    HEADING: "admin-about-heading",
    CONTENT: "admin-about-content",
  },
  USERS: {
    SECTION: "admin-users-section",
    HEADING: "admin-users-heading",
    ERROR: "admin-users-error",
    LOADING: "admin-users-loading",
    EMPTY: "admin-users-empty",
    HEADER_ROW: "admin-users-header-row",
    LIST: "admin-users-list",
    ITEM: (userId: number) => `admin-user-item-${userId}`,
  },
  DATABASE_COPY: {
    SECTION: "admin-database-copy-section",
    HEADING: "admin-database-copy-heading",
    DESCRIPTION: "admin-database-copy-description",
    ERROR: "admin-database-copy-error",
    SUCCESS: "admin-database-copy-success",
    LOADING: "admin-database-copy-loading",
    WARNING: "admin-database-copy-warning",
    MODE_OVERWRITE: "admin-database-copy-mode-overwrite",
    MODE_APPEND: "admin-database-copy-mode-append",
    RUN_BUTTON: "admin-database-copy-run-button",
  },
  UPDATES: {
    SECTION: "admin-updates-section",
    HEADING: "admin-updates-heading",
    ERROR: "admin-updates-error",
    RESULT: "admin-updates-result",
    LOADING: "admin-updates-loading",
    EMPTY: "admin-updates-empty",
    ITEM: (fileName: string) => `admin-update-item-${fileName}`,
    RERUN_CHECKBOX: (fileName: string) => `admin-update-rerun-${fileName}`,
    RUN_BUTTON: (fileName: string) => `admin-update-run-${fileName}`,
  },
  SETTINGS: {
    SECTION: "admin-settings-section",
    HEADER: "admin-settings-header",
    HEADING: "admin-settings-heading",
    DESCRIPTION: "admin-settings-description",
    ERROR: "admin-settings-error",
    SUCCESS: "admin-settings-success",
    LOADING: "admin-settings-loading",
    EMPTY: "admin-settings-empty",
    GROUP: (type: string) => `admin-settings-group-${type}`,
    SETTING: (key: string) => `admin-settings-item-${key}`,
  },
} as const;

export const ADMIN_VIEW_TEXT = {
  HOME: {
    HEADING: "Welcome",
    DESCRIPTION: "Use the left menu to switch between sections. Each section loads its own component.",
  },
  ABOUT: {
    HEADING: "About",
    LOAD_FAILED_HTML: "<p>Could not load README.md.</p>",
  },
  USERS: {
    HEADING: "Users overview",
    LOAD_FAILED: "Failed to load users",
    ID_LABEL: "ID",
    EMAIL_LABEL: "Email",
    ADMIN_LABEL: "Admin",
    NO_EMAIL: "(no email)",
    YES: "Yes",
    NO: "No",
  },
  DATABASE_COPY: {
    HEADING: "Copy production database to test database",
    DESCRIPTION: "This operation copies schema and data from production into the test database.",
    LOAD_FAILED: "Failed to load database copy status",
    COPY_FAILED: "Database copy failed",
    COPY_COMPLETED: "Database copy completed.",
    DISABLED_MESSAGE: "Database copy is disabled because required test database variables are missing.",
    MODE_LEGEND: "Choose how to run the copy",
    OVERWRITE: "Overwrite",
    OVERWRITE_DESCRIPTION: "Replace test database schema and data with production.",
    APPEND: "Append",
    APPEND_DESCRIPTION: "Keep existing test data and insert production rows where possible.",
    RUN_COPY: "Copy production to test",
    COPYING: "Copying...",
  },
  UPDATES: {
    HEADING: "Available updates",
    LOAD_FAILED: "Failed to load updates",
    RUN_FAILED: "Update execution failed",
    RUN_RESULT: "Update executed.",
    EMPTY: "No registered admin updates found.",
    UNKNOWN: "Unknown",
    FILE: "File",
    UPDATE_KEY: "Update key",
    CREATED: "Created",
    EXECUTED: "Executed",
    YES: "Yes",
    NO: "No",
    UNKNOWN_TIME: "unknown time",
    RUN_AGAIN: "Run again",
    RUN_UPDATE: "Run update",
    RUNNING: "Running...",
    RUNNING_LABEL: (fileName: string) => `Running update ${fileName}...`,
  },
  SETTINGS: {
    HEADING: "Settings",
    DESCRIPTION: "Settings are defined by YAML schemas and saved manually per group.",
    LOAD_FAILED: "Failed to load settings",
    SAVE_FAILED: "Failed to save setting",
    EMPTY: "No settings definitions found.",
    LAST_CHANGED: "Last changed:",
    NEVER: "Never",
    UNKNOWN: "Unknown",
    USER_PREFIX: "user #",
    ENABLED: "Enabled",
    SAVING_WITH_DOTS: "Saving...",
    SAVING: "Saving",
    SAVE: "Save",
    SAVED_PREFIX: "Saved",
  },
} as const;
