-- Run this in Supabase SQL editor before executing
-- ensureSettingsTableAuditColumns_1777470000.ts.

create or replace function public.ensure_settings_table_and_audit_columns_if_missing()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_regclass('public."Settings"') is null then
    execute '
      create table public."Settings" (
        id bigint generated by default as identity primary key,
        name text not null,
        type text not null,
        settings jsonb not null default ''{}''::jsonb,
        changed_by bigint references public."Users"(id),
        changed_timestamp timestamptz
      )
    ';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'Settings' and column_name = 'name'
  ) then
    execute 'alter table public."Settings" add column name text';
    execute 'update public."Settings" set name = ''default'' where name is null';
    execute 'alter table public."Settings" alter column name set not null';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'Settings' and column_name = 'type'
  ) then
    execute 'alter table public."Settings" add column type text';
    execute 'update public."Settings" set type = ''General'' where type is null';
    execute 'alter table public."Settings" alter column type set not null';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'Settings' and column_name = 'settings'
  ) then
    execute 'alter table public."Settings" add column settings jsonb not null default ''{}''::jsonb';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'Settings' and column_name = 'changed_by'
  ) then
    execute 'alter table public."Settings" add column changed_by bigint references public."Users"(id)';
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'Settings' and column_name = 'changed_timestamp'
  ) then
    execute 'alter table public."Settings" add column changed_timestamp timestamptz';
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'Settings'
      and column_name = 'changed_timestamp'
      and data_type = 'time with time zone'
  ) then
    execute '
      alter table public."Settings"
      alter column changed_timestamp type timestamptz
      using (
        case
          when changed_timestamp is null then null
          else (current_date + changed_timestamp)
        end
      )
    ';
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'Settings'
      and column_name = 'changed_timestamp'
      and data_type = 'timestamp without time zone'
  ) then
    execute '
      alter table public."Settings"
      alter column changed_timestamp type timestamptz
      using changed_timestamp at time zone ''UTC''
    ';
  end if;

  if not exists (
    select 1
    from pg_class t
    join pg_namespace ns on ns.oid = t.relnamespace
    join pg_index i on i.indrelid = t.oid
    where ns.nspname = 'public'
      and t.relname = 'Settings'
      and i.indisunique
      and i.indisvalid
      and i.indkey::int2[] = array[
        (select attnum from pg_attribute where attrelid = t.oid and attname = 'name' and not attisdropped),
        (select attnum from pg_attribute where attrelid = t.oid and attname = 'type' and not attisdropped)
      ]::int2[]
  ) then
    execute 'create unique index settings_name_type_key on public."Settings" (name, type)';
  end if;
end;
$$;

grant execute on function public.ensure_settings_table_and_audit_columns_if_missing() to service_role;
